In [1]:
import torch

data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [2]:
X = data[:, :2]
Y = data[:, 2]

In [4]:
X

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [5]:
Y

tensor([3, 4, 5])

### Weight Initialization

In [7]:

def initialize_parameters():
    parameters ={}
    parameters['w1'] = torch.ones((2,2))*0.01
    parameters['b1'] = torch.zeros((2,1))
    
    parameters['w2'] = torch.ones((2,1))*0.01
    parameters['b2'] = torch.zeros((1,1))
    return parameters

In [8]:
initialize_parameters()

{'w1': tensor([[0.0100, 0.0100],
         [0.0100, 0.0100]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.0100],
         [0.0100]]),
 'b2': tensor([[0.]])}

### batter way

In [1]:
def initialize_parameters(layer_dims):
    torch.manual_seed(3)
    parameters = {}
    L = len(layer_dims)
    
    for l in range(1, L):
        parameters['w' + str(l)] = torch.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = torch.zeros((1, layer_dims[l]))
    
    return parameters

### Forward propagation

In [2]:
def linear_forward(A, W, b):
    z = torch.mm(A, W) + b
    return z

In [ ]:
def L_layer_forward(A_prev, W, b, activation):
    