In [1]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, features):
            out = self.linear(features)
            out = self.sigmoid(out)
            
            return out

In [5]:
# create dataset
features = torch.rand(10,5)
features

tensor([[0.1327, 0.3600, 0.6493, 0.6979, 0.7463],
        [0.9405, 0.0910, 0.9330, 0.5226, 0.6397],
        [0.0713, 0.3133, 0.1632, 0.0723, 0.9263],
        [0.5839, 0.2897, 0.3814, 0.0105, 0.0732],
        [0.7327, 0.1233, 0.0935, 0.5977, 0.0975],
        [0.6631, 0.8559, 0.2784, 0.4511, 0.4392],
        [0.5803, 0.8547, 0.2516, 0.5847, 0.9095],
        [0.9490, 0.9461, 0.3086, 0.6514, 0.5908],
        [0.4645, 0.1020, 0.8389, 0.1708, 0.3918],
        [0.9892, 0.0466, 0.7186, 0.1792, 0.6164]])

In [6]:
features.shape

torch.Size([10, 5])

In [7]:
model = Model(features.shape[1])

In [8]:
model(features)

tensor([[0.3995],
        [0.3339],
        [0.5132],
        [0.4226],
        [0.3827],
        [0.4664],
        [0.4905],
        [0.4546],
        [0.3714],
        [0.3755]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.weight

Parameter containing:
tensor([[-0.1281,  0.3663, -0.4085, -0.3575,  0.2619]], requires_grad=True)

In [10]:
!pip install torchinfo

In [11]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### version 2

In [13]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        
        #layer 1
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        
        #layer 2
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, features):
            out = self.linear1(features)
            out = self.relu(out)
            out = self.linear2(out)
            out = self.sigmoid(out)
            
            return out

In [14]:
# create dataset
features = torch.rand(20,5)
features

tensor([[0.5668, 0.6050, 0.3024, 0.0515, 0.7755],
        [0.7048, 0.5957, 0.3808, 0.8571, 0.3064],
        [0.1408, 0.3841, 0.6760, 0.7022, 0.0839],
        [0.3571, 0.0794, 0.1002, 0.3920, 0.5225],
        [0.8574, 0.5669, 0.9668, 0.4484, 0.4936],
        [0.9659, 0.6986, 0.5169, 0.9050, 0.3131],
        [0.5734, 0.1092, 0.3598, 0.4933, 0.2146],
        [0.9998, 0.4632, 0.0239, 0.7226, 0.7919],
        [0.1738, 0.3750, 0.2377, 0.4320, 0.3132],
        [0.3158, 0.4801, 0.9390, 0.2585, 0.7340],
        [0.0471, 0.0448, 0.0530, 0.3227, 0.3331],
        [0.8078, 0.6099, 0.0217, 0.7806, 0.8320],
        [0.1068, 0.2390, 0.0710, 0.7865, 0.1227],
        [0.9535, 0.8179, 0.5885, 0.1809, 0.9277],
        [0.2271, 0.9665, 0.3712, 0.2240, 0.0657],
        [0.4684, 0.6997, 0.8650, 0.1162, 0.2230],
        [0.9454, 0.7107, 0.0923, 0.1403, 0.5055],
        [0.1773, 0.7259, 0.6809, 0.2750, 0.7556],
        [0.9503, 0.5172, 0.6404, 0.6044, 0.3925],
        [0.5555, 0.0486, 0.3199, 0.6834, 0.3158]])

In [17]:
model = Model(features.shape[1])

In [19]:
model.linear1.weight

Parameter containing:
tensor([[-0.2247, -0.3802, -0.0619, -0.0842, -0.3296],
        [-0.0152,  0.0323,  0.1216, -0.2983, -0.0657],
        [ 0.0133,  0.4456,  0.2751,  0.3563,  0.3112]], requires_grad=True)

In [20]:
from torchinfo import summary

summary(model, input_size=(20,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   18
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 1]                   4
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00