In [1]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, features):
            out = self.linear(features)
            out = self.sigmoid(out)
            
            return out

In [5]:
# create dataset
features = torch.rand(10,5)
features

tensor([[0.1327, 0.3600, 0.6493, 0.6979, 0.7463],
        [0.9405, 0.0910, 0.9330, 0.5226, 0.6397],
        [0.0713, 0.3133, 0.1632, 0.0723, 0.9263],
        [0.5839, 0.2897, 0.3814, 0.0105, 0.0732],
        [0.7327, 0.1233, 0.0935, 0.5977, 0.0975],
        [0.6631, 0.8559, 0.2784, 0.4511, 0.4392],
        [0.5803, 0.8547, 0.2516, 0.5847, 0.9095],
        [0.9490, 0.9461, 0.3086, 0.6514, 0.5908],
        [0.4645, 0.1020, 0.8389, 0.1708, 0.3918],
        [0.9892, 0.0466, 0.7186, 0.1792, 0.6164]])

In [6]:
features.shape

torch.Size([10, 5])

In [7]:
model = Model(features.shape[1])

In [8]:
model(features)

tensor([[0.3995],
        [0.3339],
        [0.5132],
        [0.4226],
        [0.3827],
        [0.4664],
        [0.4905],
        [0.4546],
        [0.3714],
        [0.3755]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.weight

Parameter containing:
tensor([[-0.1281,  0.3663, -0.4085, -0.3575,  0.2619]], requires_grad=True)

In [10]:
!pip install torchinfo

In [11]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00