In [3]:
import torch 
print(torch.__version__)

2.14.0+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"device name {torch.cuda.get_device_name(0)}")

In [5]:
print("CUDA available:", torch.cuda.is_available())

CUDA available: False


### creating tensors

In [6]:
a = torch.empty(2,3)
a

tensor([[-4.4757e-16,  1.2682e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.rand(2,3)

tensor([[0.0388, 0.3696, 0.9457],
        [0.3447, 0.0423, 0.8907]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3) #same random number will be generated

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([[1,2,3,], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
torch.arange(0,10,2) #start, end, step

tensor([0, 2, 4, 6, 8])

### tensors shape