In [29]:
import torch 
print(torch.__version__)

2.14.0+cpu


In [30]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"device name {torch.cuda.get_device_name(0)}")

In [31]:
print("CUDA available:", torch.cuda.is_available())

CUDA available: False


### creating tensors

In [32]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
type(a)

torch.Tensor

In [34]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.rand(2,3)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [36]:
torch.manual_seed(100)
torch.rand(2,3) #same random number will be generated

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [37]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
torch.arange(0,10,2) #start, end, step

tensor([0, 2, 4, 6, 8])

### tensors shape

In [39]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [40]:
x.shape

torch.Size([2, 3])

In [41]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
torch.rand_like(x, dtype= torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### tensors data type

In [43]:
x.dtype

torch.int64

In [44]:
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

### Mathmetical operations

In [45]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [47]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [49]:
x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[1,2,3], [4,5,6]])

In [50]:
x+y

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

### reduction operations

In [51]:
e = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.int32)

In [52]:
e

tensor([[8, 8, 4],
        [4, 1, 0]], dtype=torch.int32)

In [53]:
torch.sum(e)

tensor(25)

In [54]:
torch.mean(e.float())

tensor(4.1667)

In [55]:
torch.sum(e, dim=0) #sum of each column

tensor([12,  9,  4])